### ISSUE TITLE
Pear requires a nightly or dev version of Rust

### ISSUE THREAD

**Issue by pkozelka** [SergioBenitez/Pear#13]
I decided to try out Rocket, but during attempt to run any of its examples, I get this error on both v0.3.16 and master:

```
$ cargo run
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rocket v0.3.16 (file:///home/pk/github.com/Rocket/lib)
   Compiling rocket_codegen v0.3.16 (file:///home/pk/github.com/Rocket/codegen)
   Compiling proc-macro2 v0.4.19
   Compiling pear_codegen v0.0.20
error: failed to run custom build command for `pear_codegen v0.0.20`
process didn't exit successfully: `/home/pk/github.com/Rocket/target/debug/build/pear_codegen-9db1b986b647ff1e/build-script-build` (exit code: 101)
--- stderr
Error: Pear requires a nightly or dev version of Rust.
Installed version is: 1.28.0 (2018-07-30). Minimum required: 1.30.0-nightly (2018-08-23).
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /home/pk/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/build.rs:31:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
I believe that this package should not have such a strong requirement, as it makes it unusable with released versions of Rust.

**Comment by dtolnay** [comment]
Rocket very explicitly requires nightly so this is likely to be intentional.
See https://rocket.rs/guide/getting-started/

**Comment by pkozelka** [comment]
OK, I see, I just did not RTFM ;) thanks

**Comment by joevandyk** [comment]
Is this still the case?

```
Error: Pear requires a nightly or dev version of Rust.
Installed version is: 1.31.1 (2018-12-18). Minimum required: 1.31.0-nightly (2018-10-05).
```

**Comment by theronic** [comment]
This is a dealbreaker for using Rocket on ARMv6 (can't cross-compile).
Is there a workaround?

**Comment by ericnielsen33** [comment]
If you are using rustup, you can sync to the nightly build via the following command: -> rustup default nightly. Then test it using cargo build to confirm it compiles. If you want to lock down the version of rust / rocket, you can run the following command: -> rustup override set nightly.

**Comment by hhwyt** [comment]
> rustup default nightly

it works, thx.

**Comment by afranke** [comment]
`Installed version is: 1.42.0 (2020-03-09). Minimum required: 1.31.0-nightly (2018-10-05).` is ridiculous though. The “Minimum” requirement ostensibly is satisfied (42 >> 31).

**Comment by ilyasafzal** [comment]
Pear requires a 'dev' or 'nightly' version of rustc.
Installed version: 1.44.1 (2020-06-17)
Minimum required:  1.31.0-nightly (2018-10-05)

**Comment by slondr** [comment]
I agree that this is pretty ridiculous. Rocket doesn't require nightly Rust anymore — why does Pear?

**Comment by bakasmarius** [comment]
After some struggling to try out Rocket for the first time, I realized I had to run this command (I'm using Windows):
`rustup default nightly-x86_64-pc-windows-gnu` instead of the one I ran earlier to remove C++/Visual Studio error: `rustup default stable-x86_64-pc-windows-gnu`
I hope this comment will save someone's time and negative emotions ;)

**Comment by schubertbach2** [comment]
i am here for 5 hours and still feilure

**Comment by AuroraLantean** [comment]
rustup override set nightly

**Comment by agubelu** [comment]
I'm having the same issue, Pear requires 1.31.0-nightly and I have 1.56.1

**Comment by Nassiel** [comment]
This is really annoying and NO company is going to migrate to Rust meanwhile the big libraries force you to work in a nightly mode. Especially when the requirement behind is far passed.

**Comment by slondr** [comment]
> This is really annoying and NO company is going to migrate to Rust meanwhile the big libraries force you to work in a nightly mode. Especially when the requirement behind is far passed. 


Why would anyone in an open source project care if "big companies" use Rust?

**Comment by krysopath** [comment]
> Why would anyone in an open source project care if "big companies" use Rust?

The answer to this would not improve pear in any way.

**Comment by Nassiel** [comment]
> > This is really annoying and NO company is going to migrate to Rust meanwhile the big libraries force you to work in a nightly mode. Especially when the requirement behind is far passed.
> 
> Why would anyone in an open source project care if "big companies" use Rust?

I don't think this is the forum to discuss this, and happy to continue it on Reddit but the really short answer could be: if companies don't use rust, you are not going to get a salary as a rust developer ever. Maybe not your intention but it'd end up being a good language to play (like D) but... long live to Java 👯

**Comment by SergioBenitez** [comment]
> This is really annoying and NO company is going to migrate to Rust meanwhile the big libraries force you to work in a nightly mode. Especially when the requirement behind is far passed.

Please read my earlier comment. Neither Pear nor Rocket (0.5-rc) require nightly.

**Comment by parvizfarnia** [comment]
Hi

My environment:
```
OS : Linux Mint 20 (64 bits)
rustc --version : rustc 1.58.1 (db9d1b20b 2022-01-20) - I use the Stable Rust

```

I'm beginner in both Rust and Rocket (which I've just started learning) and I have the same issue

Here is what I have in **main.rs**

```
#[macro_use] extern crate rocket;
use rocket::form::Form;
use rocket_contrib::templates::Template;


#[get("/user/<id>")]
fn user(id: usize) -> &'static str {
    "user function called."
}

#[get("/user/<id>", rank = 2)]
fn user_int(id: isize) -> &'static str {
    "user_int called."
}

#[get("/user/<id>", rank = 1)]
fn user_str(id: &str) -> &'static str {
    "user_str called."
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![user, user_int, user_str])
}
```



And here is the content of my **Cargo.toml**
```

[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
rocket_contrib = "0.4.10"
```


And here is the error that I get when I run in the terminal **cargo run**
$ cargo run
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.36
   Compiling libc v0.2.118
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling cfg-if v1.0.0
   Compiling log v0.4.14
   Compiling yansi v0.5.0
   Compiling memchr v2.4.1
   Compiling autocfg v1.1.0
   Compiling futures-core v0.3.21
   Compiling pin-project-lite v0.2.8
   Compiling serde_derive v1.0.136
   Compiling serde v1.0.136
   Compiling bytes v1.1.0
   Compiling slab v0.4.5
   Compiling httparse v1.6.0
   Compiling hashbrown v0.11.2
   Compiling futures-sink v0.3.21
   Compiling proc-macro2 v0.4.30
   Compiling bitflags v1.3.2
   Compiling unicode-xid v0.1.0
   Compiling pin-utils v0.1.0
   Compiling itoa v1.0.1
   Compiling syn v0.15.44
   Compiling smallvec v1.8.0
   Compiling fnv v1.0.7
   Compiling percent-encoding v2.1.0
   Compiling futures-task v0.3.21
   Compiling futures-channel v0.3.21
   Compiling tinyvec_macros v0.1.0
   Compiling proc-macro-hack v0.5.19
   Compiling lazy_static v1.4.0
   Compiling futures-util v0.3.21
   Compiling version_check v0.1.5
   Compiling const_fn v0.4.9
   Compiling once_cell v1.9.0
   Compiling unicode-bidi v0.3.7
   Compiling futures-io v0.3.21
   Compiling matches v0.1.9
   Compiling try-lock v0.2.3
   Compiling safemem v0.3.3
   Compiling percent-encoding v1.0.1
   Compiling byteorder v1.4.3
   Compiling parking_lot_core v0.8.5
   Compiling inlinable_string v0.1.15
   Compiling typeable v0.1.2
   Compiling ref-cast v1.0.6
   Compiling traitobject v0.1.0
   Compiling scopeguard v1.1.0
   Compiling tower-service v0.3.1
   Compiling httpdate v1.0.2
   Compiling language-tags v0.2.2
   Compiling cfg-if v0.1.10
   Compiling mime v0.3.16
   Compiling glob v0.3.0
   Compiling state v0.4.2
   Compiling state v0.5.2
   Compiling either v1.6.1
   Compiling encoding_rs v0.8.30
   Compiling ppv-lite86 v0.2.16
   Compiling serde_json v1.0.79
   Compiling async-trait v0.1.52
   Compiling lazycell v1.3.0
   Compiling same-file v1.0.6
   Compiling ryu v1.0.9
   Compiling remove_dir_all v0.5.3
   Compiling base64 v0.13.0
   Compiling fastrand v1.7.0
   Compiling spin v0.9.2
   Compiling binascii v0.1.4
   Compiling proc-macro2-diagnostics v0.9.1
   Compiling standback v0.2.17
   Compiling time v0.2.27
   Compiling cookie v0.15.1
   Compiling uncased v0.9.6
   Compiling multer v2.0.2
   Compiling figment v0.10.6
   Compiling instant v0.1.12
   Compiling pear_codegen v0.1.4
   Compiling rocket_codegen v0.4.10
   Compiling rocket v0.4.10
   Compiling rocket v0.5.0-rc.1
   Compiling indexmap v1.8.0
   Compiling atomic v0.5.1
   Compiling http v0.2.6
   Compiling tinyvec v1.5.1
   Compiling tracing-core v0.1.22
   Compiling unicase v1.4.2
   Compiling base64 v0.9.3
   Compiling lock_api v0.4.6
   Compiling walkdir v2.3.2
error: failed to run custom build command for `pear_codegen v0.1.4`

Caused by:
  process didn't exit successfully: `/home/training/Documents/Rust/Rocket/hello-rocket/target/debug/build/pear_codegen-cffabe19d2a1cad5/build-script-build` (exit status: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.58.1 (2022-01-20)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /usr/local/rust/cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


And the same error by setting **RUST_BACKTRACE=full**

```
error: failed to run custom build command for `pear_codegen v0.1.4`

Caused by:
  process didn't exit successfully: `/home/training/Documents/Rust/Rocket/hello-rocket/target/debug/build/pear_codegen-cffabe19d2a1cad5/build-script-build` (exit status: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.58.1 (2022-01-20)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /usr/local/rust/cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24:13
  stack backtrace:
     0:     0x5557da35f97c - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5557da35f97c - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5557da35f97c - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x5557da35f97c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x5557da37d0cc - core::fmt::write::h513b07ca38f4fb1b
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
     5:     0x5557da35c3e5 - std::io::Write::write_fmt::haf8c932b52111354
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
     6:     0x5557da3610d0 - std::sys_common::backtrace::_print::h195c38364780a303
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x5557da3610d0 - std::sys_common::backtrace::print::hc09dfdea923b6730
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x5557da3610d0 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
     9:     0x5557da360c85 - std::panicking::default_hook::h60284635b0ad54a8
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
    10:     0x5557da361784 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
    11:     0x5557da32baae - std::panicking::begin_panic::{{closure}}::haa659a0e143387b5
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:526:9
    12:     0x5557da32b8f8 - std::sys_common::backtrace::__rust_end_short_backtrace::h06e345acd2ac3ed1
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
    13:     0x5557da32b9ef - std::panicking::begin_panic::hf94f072690a6f749
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:525:12
    14:     0x5557da32d27f - build_script_build::main::h508e78ef7a173979
                                 at /usr/local/rust/cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24:13
    15:     0x5557da32f18b - core::ops::function::FnOnce::call_once::h26c0ee99ba426915
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
    16:     0x5557da32b93e - std::sys_common::backtrace::__rust_begin_short_backtrace::hca0ce5045c9b9310
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
    17:     0x5557da32b651 - std::rt::lang_start::{{closure}}::h32b3d179ada8294c
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
    18:     0x5557da35f60b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
    19:     0x5557da35f60b - std::panicking::try::do_call::h4be824d2350b44c9
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
    20:     0x5557da35f60b - std::panicking::try::h0a6fc7affbe5088d
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
    21:     0x5557da35f60b - std::panic::catch_unwind::h22c320f732ec805e
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
    22:     0x5557da35f60b - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
    23:     0x5557da35f60b - std::panicking::try::do_call::h8fcaf501f097a28e
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
    24:     0x5557da35f60b - std::panicking::try::h20e906825f98acc1
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
    25:     0x5557da35f60b - std::panic::catch_unwind::h8c5234dc632124ef
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
    26:     0x5557da35f60b - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
    27:     0x5557da32b620 - std::rt::lang_start::heac8c8d471137e62
                                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144:17
    28:     0x5557da32d87c - main
    29:     0x7fe7aabe70b3 - __libc_start_main
                                 at /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    30:     0x5557da32972e - _start
    31:                0x0 - <unknown>
```



Am I missing something or is my Rust or rocket (or both) installation which is broken?

**Comment by SergioBenitez** [comment]
You're using contrib `0.4` but `rocket` `0.5`. You can't do that. See the [upgrading guide](https://rocket.rs/master/guide/upgrading-from-0.4/).

**Comment by bneijt** [comment]
I ran into this issue and found out that probably the only solution is to move to rocket 0.5 which does not depend on `pear_codegen`.

To reproduce:

    cargo new banana
    cd banana
    cargo add rocket
    cargo build

The result will be rocket `0.4.11` with the build of pear_codegen failing with:
    error: failed to run custom build command for `pear_codegen v0.1.5`
    
    Caused by:
      process didn't exit successfully: `/home/bram/tmp/banana/target/debug/build/pear_codegen-958a8fa45f97b8df/build-script-build` (exit status: 101)
      --- stderr
      Error: Pear requires a 'dev' or 'nightly' version of rustc.
      Installed version: 1.59.0 (2022-02-23)
      Minimum required:  1.31.0-nightly (2018-10-05)

The solution was to use `rocket = "0.5.0-rc.2"` as a dependency instead. I don't understand the closed upstream issue https://github.com/SergioBenitez/Pear/issues/30 but apparently it's expected behavior and if you don't want `nightly` you just don't want `pear_codegen`.
