### ISSUE TITLE
Broken on latest nightly

### ISSUE THREAD

**Issue by Deedasmi** [SergioBenitez/Pear#7]
$ rustc --version
> rustc 1.27.0-nightly (2f2a11dfc 2018-05-16)

$ rustup --version
> rustup 1.11.0 (e751ff9f8 2018-02-13)

$ cargo --version
> cargo 1.27.0-nightly (9e53ac6e6 2018-05-07)

Rocket version:
0.3.10
 
```
error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.16/src/lib.rs:317:9
    |
317 |         ExprKind::Block(block) => {
    |         ^^^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1
error: aborting due to previous error
For more information about this error, try `rustc --explain E0023`.
error: Could not compile `pear_codegen`.
```

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Pear/commit/87dbd39949604bdc2ef051ab3888495d5aa52219 and released as 0.0.17. A `cargo update` should pull the new version and resolve your issue.

**Comment by eddyb** [comment]
Random note (that doesn't have anything to do with the nightly change here):
`0.0.x` is semver-incompatible with `0.0.x+1` meaning it is impossible to release a semver-compatible update, like there is with `0.x.y` (which is semver-compatible with `0.x.y+1`).
I wish we never allowed `0.0.x` version numbers, since they provide *no* benefits over `0.x.y`, while removing *the possibility* of bugfix updates to the crate.

**Comment by SergioBenitez** [comment]
@eddyb While that's true according to the semver spec, Cargo treats them as semver compatible.

**Comment by eddyb** [comment]
@SergioBenitez I remember @steveklabnik telling me something similar and my experience being the opposite. But maybe Cargo has changed at some point?
Are you talking from docs, or from experience, and if the latter, how recent?

**Comment by steveklabnik** [comment]
The semver spec doesn't comment on ranges. It only comments on how to parse versions. Ranges are implemented by various implementations in various ways.

Semver does say

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

However, most implementations say that `0.y` is compatible with any `0.y.z` but not with `0.(y + 1)`. This is because of how most people actually use `x=0` versions in the wild.
